### ISSUE TITLE
GoogleFonts() breaks `next build`

### ISSUE THREAD

**Issue by roderik** [krychaxp/nextjs-google-fonts#2]
The downloading part works, the fonts are in the public folder.

Running `next build` errors like this.

```
$ next build
info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
Error: Failed to load /_app
    at loadComponents (/Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/next-server/server/load-components.js:1:1554)
    at hasCustomGetInitialProps (/Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/build/utils.js:26:1315)
    at /Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/build/index.js:19:123
    at async Span.traceAsyncFn (/Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/build/index.js:17:2153
    at async Span.traceAsyncFn (/Users/roderik/Development/scb-asset-tokenization-platform/usecases/wealthmanagementbonds/dapp/node_modules/next/dist/telemetry/trace/trace.js:6:584)
error Command failed with exit code 1.
```

If I start with `yarn dev` it does the same, until it prints `[nextjs-google-fonts] Successfully end!`
After that, `yarn build` also works

**Comment by roderik** [comment]
```
import type { AppProps } from 'next/app';
import { Provider } from 'next-auth/client';
import React from 'react';
import { AuthProvider } from '../providers/AuthProvider';

import 'tailwindcss/tailwind.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider session={pageProps.session}>
      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
    </Provider>
  );
}

export default MyApp;
```

**Comment by krychaxp** [comment]
but without nextjs-google-fonts your app works, yes? 🤔

**Comment by roderik** [comment]
Yes, and with it as well, but not before it is done caching the fonts and writes the data json file. 

It would be better if this would be a blocking action or is mentioned that you will see a bunch of errors until it is done, and probably that you need to commit the cached fonts in your git repo since `build` will not work (on e.g. a CI) without giving `dev` time to cache the fonts.

**Comment by krychaxp** [comment]
i dont think then you must cached fonts in your repo (i dont cache it in my project and it works), because downloaded fonts time is less then `next build` time

**Comment by krychaxp** [comment]
i have just updated package and add some providers and handle errors

**Comment by krychaxp** [comment]
@roderik do you fix this problem?

**Comment by roderik** [comment]
I had to leave the frontend lie for a bit, will be picking it up again this week.

**Comment by roderik** [comment]
yes
